version: '3.8'

services:
	db:
		image: postgres:16-alpine
		container_name: postgres_db
		environment:
			POSTGRES_DB: alx_properties_db
			POSTGRES_USER: alx_user
			POSTGRES_PASSWORD: alx_password
		ports:
			- "5432:5432" # Host:Container
		volumes:
			- postgres_data:/var/lib/postgresql/data/

	redis:
		image: redis:7-alpine
		container_name: redis_cache
		ports:
			- "6379:6379"
		command: redis-server --appendlonly yes
		volumes:
			- redis_data:/data
